module.exports = (sequelize, Sequelize) => {
  const Match = sequelize.define("matches", {
    id: { type: Sequelize.INTEGER, primaryKey: true },
    year: { type: Sequelize.INTEGER },
    round: { type: Sequelize.INTEGER },
    is_final: { type: Sequelize.INTEGER },
    hteam: { type: Sequelize.STRING },
    hgoals: { type: Sequelize.INTEGER },
    hbehinds: { type: Sequelize.INTEGER },
    hscore: { type: Sequelize.INTEGER },
    ateam: { type: Sequelize.STRING },
    agoals: { type: Sequelize.INTEGER },
    abehinds: { type: Sequelize.INTEGER },
    ascore: { type: Sequelize.INTEGER },
    venue: { type: Sequelize.STRING },
    date: { type: Sequelize.STRING },
    complete: { type: Sequelize.INTEGER },
    winner: { type: Sequelize.STRING },
    unixtime: { type: Sequelize.INTEGER },
    localtime: { type: Sequelize.STRING },
    timestr: { type: Sequelize.STRING },
    hteamid: { type: Sequelize.INTEGER },
    ateamid: { type: Sequelize.INTEGER },
    winnerteamid: { type: Sequelize.INTEGER },
    is_grand_final: { type: Sequelize.INTEGER },
    roundname: { type: Sequelize.STRING },
    updated: { type: Sequelize.STRING },
    tz: { type: Sequelize.STRING },
  });
  return Match;
};
